# Write your MySQL query statement below
### 两次连接操作
SELECT C.NAME AS Department, D.NAME AS Employee, D.Salary FROM 
EMPLOYEE AS D JOIN 
(SELECT A.ID, A.NAME, B.MAXS FROM 
   DEPARTMENT AS A JOIN (SELECT MAX(SALARY) AS MAXS, DEPARTMENTID FROM EMPLOYEE GROUP BY DEPARTMENTID) AS B 
     ON A.ID = B.DEPARTMENTID) AS C 
ON D.DEPARTMENTID = C.ID WHERE D.SALARY = C.MAXS